FROM ubuntu:16.04
MAINTAINER Derek Bourgeois <debourge@cisco.com>

# update the container
RUN apt-get update && \
    apt-get upgrade -y

# install some basics
RUN apt-get install -y software-properties-common
